name: CI

on:
  push:
    tags:
      - "v*"
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.71.1
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Build with UMA2
      run: cargo build --features uma2
    - name: Run tests with UMA2
      run: cargo test --features uma2
    - name: Build with Microsoft feature
      run: cargo build --features microsoft
    - name: Run tests with Microsoft feature
      run: cargo test --features uma2
    - name: Build with rustls
      run: cargo build --no-default-features --features rustls
    - name: Run tests with rustls
      run: cargo test --no-default-features --features rustls
  publish:
    name: Publish
    if: startsWith( github.ref, 'refs/tags/v' )
    uses: ./.github/workflows/release.yml
    needs: build
    secrets: inherit